### ISSUE TITLE
Will not compile on M1 MacBook 

### ISSUE THREAD

**Issue by genedelisa** [brightdigit/EggSeed#15]
Environment: macOS 11.4, MacBook Pro (13-inch, M1, 2020)
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)
Target: arm64-apple-darwin20.5.0

I followed these simple instructions from the README:

- git clone https://github.com/brightdigit/EggSeed.git
- cd EggSeed
- swift run eggseed

That is all that I did. No modifications by me.
Did I miss something or are there other steps the README misses?

After the fetches etc. the compile job barfs with this:

Cloning https://github.com/Quick/Nimble
Resolving https://github.com/Quick/Nimble at 8.1.2
While building module 'std' imported from /Library/Developer/CommandLineTools/usr/include/c++/v1/stdint.h:123:
While building module 'Darwin' imported from /Library/Developer/CommandLineTools/usr/include/c++/v1/ctype.h:38:
In file included from <module-includes>:30:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.5/include/tgmath.h:21:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/tgmath.h:31:10: fatal error: cyclic dependency in module 'std': std -> Darwin -> std
#include <complex.h>
         ^
While building module 'std' imported from /Library/Developer/CommandLineTools/usr/include/c++/v1/stdint.h:123:
In file included from <module-includes>:1:
/Library/Developer/CommandLineTools/usr/include/c++/v1/ctype.h:38:15: fatal error: could not build module 'Darwin'
#include_next <ctype.h>
 ~~~~~~~~~~~~~^
In file included from /Users/genedelisa/Development/others/Apple/EggSeed/.build/checkouts/swift-syntax/Sources/_CSwiftSyntax/src/atomic-counter.c:1:
In file included from /Users/genedelisa/Development/others/Apple/EggSeed/.build/checkouts/swift-syntax/Sources/_CSwiftSyntax/include/atomic-counter.h:1:
/Library/Developer/CommandLineTools/usr/include/c++/v1/stdint.h:123:15: fatal error: could not build module 'std'
#include_next <stdint.h>
 ~~~~~~~~~~~~~^
3 errors generated.
[0/87] Compiling atomic-counter.c
error: fatalError

**Comment by leogdion** [comment]
I don't get that on my M1. I would look at clearing your Swift package cache. It may be something with Nimble possibly.
https://stackoverflow.com/questions/60033082/how-can-i-reset-the-package-cache-on-just-one-package-with-swift-package-manager
